const root=document.documentElement;
const themeToggle=document.getElementById('themeToggle');
const savedTheme=localStorage.getItem('theme');
if(savedTheme)root.dataset.theme=savedTheme;
const syncThemeIcon=()=>themeToggle.textContent=root.dataset.theme==='light'?'☾':'☀';
syncThemeIcon();
themeToggle.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='light'?'dark':'light';localStorage.setItem('theme',root.dataset.theme);syncThemeIcon()});
const menuToggle=document.getElementById('menuToggle');
const navLinks=document.getElementById('navLinks');
menuToggle.addEventListener('click',()=>navLinks.classList.toggle('open'));
navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const counterObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const el=entry.target;const target=Number(el.dataset.count);const decimals=Number.isInteger(target)?0:2;let value=0;const step=target/45;const timer=setInterval(()=>{value=Math.min(target,value+step);el.textContent=value.toFixed(decimals);if(value>=target)clearInterval(timer)},24);counterObserver.unobserve(el)}),{threshold:.6});
document.querySelectorAll('[data-count]').forEach(el=>counterObserver.observe(el));
const filters=document.querySelectorAll('.filter');
const projects=document.querySelectorAll('.project-card');
filters.forEach(button=>button.addEventListener('click',()=>{filters.forEach(item=>item.classList.remove('active'));button.classList.add('active');const value=button.dataset.filter;projects.forEach(card=>{card.hidden=value!=='all'&&!card.dataset.category.split(' ').includes(value)})}));
window.addEventListener('scroll',()=>{const height=document.documentElement.scrollHeight-window.innerHeight;document.getElementById('scrollProgress').style.width=`${height?window.scrollY/height*100:0}%`});
document.getElementById('contactForm').addEventListener('submit',event=>{event.preventDefault();const name=encodeURIComponent(document.getElementById('name').value.trim());const email=encodeURIComponent(document.getElementById('email').value.trim());const message=encodeURIComponent(document.getElementById('message').value.trim());window.location.href=`mailto:Ricardoavalos14@icloud.com?subject=${encodeURIComponent(`Portfolio inquiry from ${decodeURIComponent(name)}`)}&body=${encodeURIComponent(`Name: ${decodeURIComponent(name)}\nEmail: ${decodeURIComponent(email)}\n\n${decodeURIComponent(message)}`)}`});
document.getElementById('year').textContent=new Date().getFullYear();
